# open terminal and run the following:
cd c:\udacity-courses
cd car-nd-udacity
cd P10-MPC
cd docker
docker build -t akpmc .
docker run -it -p 4567:4567 akpmc /bin/bash

	# needed to make the ipopt work
	sudo ldconfig

	# Cloning project
	mkdir project
	cd project
	git clone https://github.com/khalilia2000/Car-ND-Model-Predictive-Control.git

	# Building the Project
	cd Car-ND-Model-Predictive-Control
	mkdir build
	cd build
	cmake ..
	make

docker login
docker tag akpmc khalilia2000/ak-pmc:tag
docker push khalilia2000/ak-pmc:tag